---
name: dev-release

on:
  # test
  push:
  # endtest
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.scality.com
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # context: .
          # file: ./Dockerfile
          push: true
          # test
          tags: "registry.scality.com/test-result-management-dev/test-result-management:test_push_action"
          # endtest
          # tags: "registry.scality.com/test-result-management-dev/test-result-management:${{ github.event.inputs.tag }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
